-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1035
--   at:        2018-05-04 16:47:05 AEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

DROP sequence sarms_sarms_id_seq;
DROP sequence lecture_id_seq;
DROP sequence enrollments_enrollment_id_seq;
DROP sequence email_id_seq;


DROP TABLE assignment CASCADE CONSTRAINTS;

DROP TABLE email CASCADE CONSTRAINTS;

DROP TABLE enrollments CASCADE CONSTRAINTS;

DROP TABLE lecture CASCADE CONSTRAINTS;

DROP TABLE sarms_user CASCADE CONSTRAINTS;

DROP TABLE student_at_risk CASCADE CONSTRAINTS;

DROP TABLE unit CASCADE CONSTRAINTS;

CREATE TABLE assignment (
    assignment_id     VARCHAR2(10) NOT NULL,
    due_date          DATE,
    assignment_name   VARCHAR2(100),
    unit_id           VARCHAR2(10) NOT NULL
)
LOGGING;

ALTER TABLE assignment ADD CONSTRAINT assignment_pk PRIMARY KEY ( assignment_id );

CREATE TABLE email (
    id       NUMBER NOT NULL,
    email    VARCHAR2(500),
    "date"   DATE,
    sar_id   NUMBER NOT NULL
)
LOGGING;

ALTER TABLE email ADD CONSTRAINT email_pk PRIMARY KEY ( id );

CREATE TABLE enrollments (
    enrollment_id   NUMBER NOT NULL,
    student_id      VARCHAR2(10) NOT NULL,
    unit_id         VARCHAR2(10) NOT NULL
)
LOGGING;

ALTER TABLE enrollments ADD CONSTRAINT enrollments_pk PRIMARY KEY ( enrollment_id );

CREATE TABLE lecture (
    id         NUMBER NOT NULL,
    "date"     DATE,
    "number"   INTEGER,
    unit_id    VARCHAR2(10) NOT NULL
)
LOGGING;

ALTER TABLE lecture ADD CONSTRAINT lecture_pk PRIMARY KEY ( id );

CREATE TABLE sarms_user (
    user_id          VARCHAR2(10) NOT NULL,
    fname            VARCHAR2(20) NOT NULL,
    lname            VARCHAR2(20) NOT NULL,
    email            VARCHAR2(100) NOT NULL,
    phone1           VARCHAR2(20),
    phone2           VARCHAR2(20),
    user_type        VARCHAR2(10),
    salty_password   VARCHAR2(200),
    user_salt        VARCHAR2(100)
)
LOGGING;

COMMENT ON COLUMN sarms_user.user_type IS
    'int 1 denotes admin
int 2 denotes lecturer
int 3 denotes student
Could break these out into tables but easy to code this way and a small amount redundancy permitted'
;

ALTER TABLE sarms_user ADD CONSTRAINT sarms_user_pk PRIMARY KEY ( user_id );

CREATE TABLE student_at_risk (
    sarms_id           NUMBER NOT NULL,
    enrollment_id      NUMBER NOT NULL,
    lecturer_id        VARCHAR2(10) NOT NULL,
    admin_id           VARCHAR2(10) NOT NULL,
    risk_description   VARCHAR2(50) NOT NULL
)
LOGGING;

ALTER TABLE student_at_risk ADD CONSTRAINT student_at_risk_pk PRIMARY KEY ( sarms_id );

CREATE TABLE unit (
    unit_id     VARCHAR2(10) NOT NULL,
    lecturer    VARCHAR2(10) NOT NULL,
    unit_name   VARCHAR2(100)
)
LOGGING;

ALTER TABLE unit ADD CONSTRAINT unit_pk PRIMARY KEY ( unit_id );

ALTER TABLE assignment
    ADD CONSTRAINT assignment_unit_fk FOREIGN KEY ( unit_id )
        REFERENCES unit ( unit_id )
    NOT DEFERRABLE;

ALTER TABLE email
    ADD CONSTRAINT email_student_at_risk_fk FOREIGN KEY ( sar_id )
        REFERENCES student_at_risk ( sarms_id )
    NOT DEFERRABLE;

ALTER TABLE enrollments
    ADD CONSTRAINT enrollments_sarms_user_fk FOREIGN KEY ( student_id )
        REFERENCES sarms_user ( user_id )
    NOT DEFERRABLE;

ALTER TABLE enrollments
    ADD CONSTRAINT enrollments_unit_fk FOREIGN KEY ( unit_id )
        REFERENCES unit ( unit_id )
    NOT DEFERRABLE;

ALTER TABLE lecture
    ADD CONSTRAINT lecture_unit_fk FOREIGN KEY ( unit_id )
        REFERENCES unit ( unit_id )
    NOT DEFERRABLE;

ALTER TABLE student_at_risk
    ADD CONSTRAINT sar_sarms_user_admin_fk FOREIGN KEY ( admin_id )
        REFERENCES sarms_user ( user_id )
    NOT DEFERRABLE;

ALTER TABLE student_at_risk
    ADD CONSTRAINT sar_sarms_user_lect_fk FOREIGN KEY ( lecturer_id )
        REFERENCES sarms_user ( user_id )
    NOT DEFERRABLE;

ALTER TABLE student_at_risk
    ADD CONSTRAINT student_at_risk_enrollments_fk FOREIGN KEY ( enrollment_id )
        REFERENCES enrollments ( enrollment_id )
    NOT DEFERRABLE;

ALTER TABLE unit
    ADD CONSTRAINT unit_sarms_user_fk FOREIGN KEY ( lecturer )
        REFERENCES sarms_user ( user_id )
    NOT DEFERRABLE;

CREATE SEQUENCE email_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER email_id_trg BEFORE
    INSERT ON email
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := email_id_seq.nextval;
END;
/

CREATE SEQUENCE enrollments_enrollment_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER enrollments_enrollment_id_trg BEFORE
    INSERT ON enrollments
    FOR EACH ROW
    WHEN ( new.enrollment_id IS NULL )
BEGIN
    :new.enrollment_id := enrollments_enrollment_id_seq.nextval;
END;
/

CREATE SEQUENCE lecture_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER lecture_id_trg BEFORE
    INSERT ON lecture
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := lecture_id_seq.nextval;
END;
/

CREATE SEQUENCE sarms_sarms_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER sarms_sarms_id_trg BEFORE
    INSERT ON student_at_risk
    FOR EACH ROW
    WHEN ( new.sarms_id IS NULL )
BEGIN
    :new.sarms_id := sarms_sarms_id_seq.nextval;
END;
/
